# Generated by Django 4.0 on 2021-12-26 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='API.question', verbose_name='Идентификатор вопроса'),
        ),
        migrations.AlterField(
            model_name='question',
            name='poll_relation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll', to='API.poll', verbose_name='Вопрос из опроса'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('TX', 'Text'), ('OC', 'OneChoice'), ('MC', 'ManyChoices')], max_length=2, verbose_name='Тип вопроса'),
        ),
    ]
